# Lab 2 – Tensors

In [1]:
# Import PyTorch
import torch

## Create empty tensors
- Uninitialised tensors

In [2]:
# 1-D
x = torch.empty(1)
print(x)

# 1-D with two elements
x = torch.empty(2)
print(f"\n1-D tensor\n{x}\n")

# 2-D
x = torch.empty(2,3)
print(f"2-D tensor\n{x}\n")

# 3-D
x = torch.empty(2,3,1)
print("3-D tensor\n",x)


tensor([1.5358e-42])

1-D tensor
tensor([1.9386e+26, 4.5797e-41])

2-D tensor
tensor([[1.0576e-34, 0.0000e+00, 1.0575e-34],
        [0.0000e+00, 8.9683e-44, 0.0000e+00]])

3-D tensor
 tensor([[[1.0579e-34],
         [0.0000e+00],
         [1.0578e-34]],

        [[0.0000e+00],
         [0.0000e+00],
         [0.0000e+00]]])


## Initialise tensors to scalar, random values, zeros or ones

In [3]:
# 0-D tensor (just containing scalar value 3)
x = torch.tensor(3)
# print(x)
print(f'Scalar: {x} has shape {x.shape} and {x.ndim} dimensions\n')

# Random values in the interval [0,1]
x = torch.rand(2,3)
print(f"Random values:\n{x}")
print(x.dtype)

# Zeros
x = torch.zeros(2,3)
print(f"\nZeros:\n{x}")
print(x.dtype)

x = torch.zeros(2,3, dtype=torch.int)
print(f"\nZeros:\n{x}\n")

# Ones
x = torch.ones(2,3)
print(f"Ones:\n{x}")
print(f"Type: {x.dtype}\n")

x = torch.ones(2,3, dtype=torch.double)
print(f"Ones:\n{x}")

Scalar: 3 has shape torch.Size([]) and 0 dimensions

Random values:
tensor([[0.1728, 0.7560, 0.7153],
        [0.5225, 0.8703, 0.1590]])
torch.float32

Zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.float32

Zeros:
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

Ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type: torch.float32

Ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


## Construct tensor from data

In [4]:
# Change a list to a tensor
x = torch.tensor([0.5, 2.7])
print(x)

tensor([0.5000, 2.7000])


### Changing tensor data type


In [5]:
x = torch.rand(2,3) * 20
print(x)

# Change to integer
y = x.to(torch.int32)
print(y)

tensor([[13.1654, 14.2761, 19.5872],
        [10.5429,  1.6678, 15.8941]])
tensor([[13, 14, 19],
        [10,  1, 15]], dtype=torch.int32)


### Create a separate copy



In [6]:
a = torch.ones(2, 2)
b = a.clone()

a[0][1] = 561          # a changes...
print(b)               # ...but b is still all ones

tensor([[1., 1.],
        [1., 1.]])


## Basic tensor operations

- addition, subtraction, multiplication, division

In [7]:
x = torch.rand(2,2)
print(f"x = \n{x}\n")

y = torch.rand(2,2)
print(f"y = \n{y}\n")

z = torch.add(x,y) # same as z = x + y
print("x + y = ")
print(z)

z = torch.sub(x,y) # same as z = x - y
print("x - y = ")
print(z)

z = torch.mul(x,y) # same as z = x * y
print("x * y = ")
print(z)

z = torch.div(x,y) # same as z = x / y
print("x / y = ")
print(z)


x = 
tensor([[0.2158, 0.9638],
        [0.1790, 0.8558]])

y = 
tensor([[0.5872, 0.4572],
        [0.1490, 0.2981]])

x + y = 
tensor([[0.8030, 1.4210],
        [0.3280, 1.1539]])
x - y = 
tensor([[-0.3714,  0.5066],
        [ 0.0300,  0.5578]])
x * y = 
tensor([[0.1267, 0.4406],
        [0.0267, 0.2551]])
x / y = 
tensor([[0.3675, 2.1081],
        [1.2016, 2.8714]])


### Inplace operations

- any function with a trailing underscore (e.g. ``add_``) will modify the value of the variable in question, in place

In [8]:
x = torch.rand(2,2)
print(f"x = \n{x}\n")

y = torch.rand(2,2)
print(f"y = \n{y}\n")

# Inplace operations
y.add_(x) # modify y by adding x to it
print(f"y + x = {y}")

y.sub_(x) # modify y by subtracting x from it
print(f"y - x = {y}")

y.mul_(x) # modify y by multiplying x to it
print(f"y * x = {y}")

y.div_(x) # modify y by dividing it by x
print(f"y / x = {y}")


x = 
tensor([[0.0139, 0.8906],
        [0.1561, 0.4241]])

y = 
tensor([[0.4132, 0.7888],
        [0.8825, 0.7705]])

y + x = tensor([[0.4271, 1.6795],
        [1.0386, 1.1947]])
y - x = tensor([[0.4132, 0.7888],
        [0.8825, 0.7705]])
y * x = tensor([[0.0058, 0.7026],
        [0.1378, 0.3268]])
y / x = tensor([[0.4132, 0.7888],
        [0.8825, 0.7705]])


## Accessing tensors

In [9]:
# Slicing
x = torch.rand(5,3)
print(x)

# Get all rows but only first column
print(x[:, 0])

# Get all columns but only the second row
print(x[1, :])

# Get a specific element
print(x[2,2])

# When the tensor returns only ONE element, use item() to get the actual value of that element
print(x[1,1].item())

y = torch.tensor([2.0])
print(y.item())

tensor([[0.6961, 0.6261, 0.1393],
        [0.2698, 0.3240, 0.4974],
        [0.5118, 0.2450, 0.4720],
        [0.0928, 0.6432, 0.5398],
        [0.5806, 0.4755, 0.5905]])
tensor([0.6961, 0.2698, 0.5118, 0.0928, 0.5806])
tensor([0.2698, 0.3240, 0.4974])
tensor(0.4720)
0.32401543855667114
2.0


## Tensor Shape & Dimensions
- The number of dimensions a tensor has is called its rank and the length in each dimension describes its ``shape``.
- To determine the length of each dimension, call ``.shape``
- To determine the number of dimensions it has, call ``.ndim``


In [10]:
x = torch.rand(5,3)
print(f'{x} \nhas shape {x.shape} and {x.ndim} dimensions\n')

tensor([[0.4753, 0.5332, 0.8749],
        [0.1550, 0.4504, 0.1563],
        [0.8405, 0.6950, 0.1310],
        [0.7475, 0.1949, 0.3907],
        [0.2564, 0.3651, 0.9859]]) 
has shape torch.Size([5, 3]) and 2 dimensions



## More on Shapes

- `[1,5,2,6]` has shape (4,) to indicate it has 4 elements and the missing element after the comma means it is a 1-D tensor or array (vector)
- `[[1,5,2,6], [1,2,3,1]]` has shape (2,4) to indicate it has 2 elements (rows) and each of these have 4 elements (columns). This is a 2-D tensor or array (matrix or a list of vectors)
- `[[[1,5,2,6], [1,2,3,1]], [[5,2,1,2], [6,4,3,2]], [[7,8,5,3], [2,2,9,6]]]` has shape (3, 2, 4) to indicate it has 3 elements in the first dimension, and each of these contain 2 elements and each of these contain 4 elements. This is a 3-D tensor or array


## Operations on tensor dimensions
- A tensor dimension is akin to an array's axis. The number of dimensions is called rank.
- A scalar has rank 0, a vector has rank 1, a matrix has rank 2, a cuboid has rank 3, etc.
- Sometimes one wants to do an operation only on a particular dimension, e.g. on the rows only
- Across ``dim=X`` means we do the operation w.r.t to the dimension given and the rest of the dimensions of the tensor stays as they are
- in 2-D tensors, ``dim=0`` refers to the columns while ``dim=1`` refers to the rows


In [11]:
x = torch.tensor([[1,2,3],
                 [4,5,6]])

print(x.shape)
print(f'Summing across dim=0 (columns) gives: {torch.sum(x,dim=0)}')

print(f'Summing across dim=1 (rows) gives: {torch.sum(x,dim=1)}')


torch.Size([2, 3])
Summing across dim=0 (columns) gives: tensor([5, 7, 9])
Summing across dim=1 (rows) gives: tensor([ 6, 15])


## Reshaping tensors
- There are several ways to do this but using ``torch.reshape()`` is the most common
- Also look up ``torch.squeeze(), torch.unsqueeze()`` and ``torch.view()``


In [12]:
x = torch.rand(4,4)
print("Original:")
print(x)
print(x.shape)

# Reshape (flatten) to 1-D
y = x.reshape(16) # number of elements must be the same as original, error otherwise
print("Reshaped to 1-D:")
print(y)

# Reshape to 2-D
y = x.reshape(8,2)
print("Reshaped to 2-D:")
print(y)

# Could leave out one of the dimensions by specifying -1
y = x.reshape(2, -1)
print("Reshaped to 2 x Unspecified 2-D:")
print(y)
print(y.shape)

# Could use unsqueeze(0) to add a dimension at position 0
y = x.unsqueeze(0)
print(f'Using unsqueeze(0) to add dimension from original shape {x.shape} to {y.shape}')

Original:
tensor([[0.6651, 0.2381, 0.8381, 0.7980],
        [0.9020, 0.8299, 0.4397, 0.3118],
        [0.4652, 0.4627, 0.0615, 0.2425],
        [0.2496, 0.7957, 0.4714, 0.2595]])
torch.Size([4, 4])
Reshaped to 1-D:
tensor([0.6651, 0.2381, 0.8381, 0.7980, 0.9020, 0.8299, 0.4397, 0.3118, 0.4652,
        0.4627, 0.0615, 0.2425, 0.2496, 0.7957, 0.4714, 0.2595])
Reshaped to 2-D:
tensor([[0.6651, 0.2381],
        [0.8381, 0.7980],
        [0.9020, 0.8299],
        [0.4397, 0.3118],
        [0.4652, 0.4627],
        [0.0615, 0.2425],
        [0.2496, 0.7957],
        [0.4714, 0.2595]])
Reshaped to 2 x Unspecified 2-D:
tensor([[0.6651, 0.2381, 0.8381, 0.7980, 0.9020, 0.8299, 0.4397, 0.3118],
        [0.4652, 0.4627, 0.0615, 0.2425, 0.2496, 0.7957, 0.4714, 0.2595]])
torch.Size([2, 8])
Using unsqueeze(0) to add dimension from original shape torch.Size([4, 4]) to torch.Size([1, 4, 4])


## Convert between NumPy and PyTorch tensors

- Tensors can work on CPUs and GPUs
- NumPy arrays can only work on CPUs

In [13]:
import torch
import numpy as np

# Tensor to NumPy
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)
print(type(b))

# b changes when a is modified because they share the same memory space!
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [14]:
import torch
import numpy as np

a = np.ones(5)
print(a)

b = torch.from_numpy(a)
print(b)

# Modifying array will modify the tensor as well
a += 2
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[3. 3. 3. 3. 3.]
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


# Exercise

In [15]:
# 1. Create a tensor of 100 equally spaced numbers from 0 to 2.
# Assign the tensor to x (Hint: use torch.linspace() )
x = torch.linspace(0,2,100)
# Print x
print(x)

tensor([0.0000, 0.0202, 0.0404, 0.0606, 0.0808, 0.1010, 0.1212, 0.1414, 0.1616,
        0.1818, 0.2020, 0.2222, 0.2424, 0.2626, 0.2828, 0.3030, 0.3232, 0.3434,
        0.3636, 0.3838, 0.4040, 0.4242, 0.4444, 0.4646, 0.4848, 0.5051, 0.5253,
        0.5455, 0.5657, 0.5859, 0.6061, 0.6263, 0.6465, 0.6667, 0.6869, 0.7071,
        0.7273, 0.7475, 0.7677, 0.7879, 0.8081, 0.8283, 0.8485, 0.8687, 0.8889,
        0.9091, 0.9293, 0.9495, 0.9697, 0.9899, 1.0101, 1.0303, 1.0505, 1.0707,
        1.0909, 1.1111, 1.1313, 1.1515, 1.1717, 1.1919, 1.2121, 1.2323, 1.2525,
        1.2727, 1.2929, 1.3131, 1.3333, 1.3535, 1.3737, 1.3939, 1.4141, 1.4343,
        1.4545, 1.4747, 1.4949, 1.5152, 1.5354, 1.5556, 1.5758, 1.5960, 1.6162,
        1.6364, 1.6566, 1.6768, 1.6970, 1.7172, 1.7374, 1.7576, 1.7778, 1.7980,
        1.8182, 1.8384, 1.8586, 1.8788, 1.8990, 1.9192, 1.9394, 1.9596, 1.9798,
        2.0000])


In [16]:
# 2. Print the first 5 numbers in x.
print(x[0:5])
# 3. Print the last 5 numbers in x
print(x[-5:])

tensor([0.0000, 0.0202, 0.0404, 0.0606, 0.0808])
tensor([1.9192, 1.9394, 1.9596, 1.9798, 2.0000])


In [23]:
# 4. Create another tensor of 100 random values between 0 and 1.
# Assign the tensor to y (Hint: use torch.rand() )
y = torch.rand(1,100)
# Print y
print(y)

tensor([[0.1312, 0.6834, 0.6897, 0.7229, 0.7533, 0.7509, 0.2902, 0.5940, 0.7581,
         0.4416, 0.9319, 0.4521, 0.0040, 0.8509, 0.6124, 0.1526, 0.8414, 0.9621,
         0.7298, 0.6430, 0.3393, 0.8167, 0.1615, 0.5192, 0.4703, 0.4116, 0.9477,
         0.7861, 0.2874, 0.6741, 0.1765, 0.6339, 0.9557, 0.0565, 0.5206, 0.3497,
         0.2230, 0.9083, 0.8415, 0.5499, 0.0416, 0.8444, 0.7091, 0.8424, 0.8279,
         0.4997, 0.7742, 0.1354, 0.4119, 0.2141, 0.2999, 0.6154, 0.6874, 0.9861,
         0.6155, 0.4593, 0.1365, 0.2077, 0.3198, 0.4392, 0.1352, 0.5732, 0.3140,
         0.8738, 0.4046, 0.7444, 0.1324, 0.8559, 0.1846, 0.7608, 0.5791, 0.3086,
         0.9585, 0.2777, 0.0949, 0.8875, 0.5546, 0.9507, 0.7123, 0.4355, 0.0591,
         0.2861, 0.3471, 0.5294, 0.0122, 0.1662, 0.2314, 0.9300, 0.0136, 0.0575,
         0.8314, 0.8152, 0.4619, 0.5606, 0.4056, 0.0839, 0.7641, 0.9671, 0.5905,
         0.2117]])


In [25]:
# 5. Multiply x and y, store the result in z
z = x.mul(y)
# Print z
print(z)

tensor([[0.0000e+00, 1.3805e-02, 2.7868e-02, 4.3810e-02, 6.0870e-02, 7.5849e-02,
         3.5173e-02, 8.3995e-02, 1.2252e-01, 8.0283e-02, 1.8827e-01, 1.0047e-01,
         9.7659e-04, 2.2346e-01, 1.7322e-01, 4.6248e-02, 2.7197e-01, 3.3043e-01,
         2.6537e-01, 2.4681e-01, 1.3709e-01, 3.4649e-01, 7.1790e-02, 2.4125e-01,
         2.2803e-01, 2.0790e-01, 4.9781e-01, 4.2878e-01, 1.6260e-01, 3.9493e-01,
         1.0698e-01, 3.9700e-01, 6.1780e-01, 3.7665e-02, 3.5760e-01, 2.4723e-01,
         1.6216e-01, 6.7896e-01, 6.4600e-01, 4.3326e-01, 3.3584e-02, 6.9944e-01,
         6.0168e-01, 7.3181e-01, 7.3591e-01, 4.5424e-01, 7.1947e-01, 1.2861e-01,
         3.9944e-01, 2.1196e-01, 3.0296e-01, 6.3400e-01, 7.2208e-01, 1.0558e+00,
         6.7141e-01, 5.1035e-01, 1.5445e-01, 2.3923e-01, 3.7473e-01, 5.2344e-01,
         1.6393e-01, 7.0633e-01, 3.9330e-01, 1.1121e+00, 5.2315e-01, 9.7753e-01,
         1.7648e-01, 1.1585e+00, 2.5359e-01, 1.0605e+00, 8.1897e-01, 4.4267e-01,
         1.3942e+00, 4.0960e

In [29]:
from numpy.core.fromnumeric import shape
# 6. Reshape z to a tensor with 5 rows and 20 columns
# Store reshaped tensor to z2
z2 = z.reshape(5,20)
# Print z2
print(z2)

tensor([[0.0000e+00, 1.3805e-02, 2.7868e-02, 4.3810e-02, 6.0870e-02, 7.5849e-02,
         3.5173e-02, 8.3995e-02, 1.2252e-01, 8.0283e-02, 1.8827e-01, 1.0047e-01,
         9.7659e-04, 2.2346e-01, 1.7322e-01, 4.6248e-02, 2.7197e-01, 3.3043e-01,
         2.6537e-01, 2.4681e-01],
        [1.3709e-01, 3.4649e-01, 7.1790e-02, 2.4125e-01, 2.2803e-01, 2.0790e-01,
         4.9781e-01, 4.2878e-01, 1.6260e-01, 3.9493e-01, 1.0698e-01, 3.9700e-01,
         6.1780e-01, 3.7665e-02, 3.5760e-01, 2.4723e-01, 1.6216e-01, 6.7896e-01,
         6.4600e-01, 4.3326e-01],
        [3.3584e-02, 6.9944e-01, 6.0168e-01, 7.3181e-01, 7.3591e-01, 4.5424e-01,
         7.1947e-01, 1.2861e-01, 3.9944e-01, 2.1196e-01, 3.0296e-01, 6.3400e-01,
         7.2208e-01, 1.0558e+00, 6.7141e-01, 5.1035e-01, 1.5445e-01, 2.3923e-01,
         3.7473e-01, 5.2344e-01],
        [1.6393e-01, 7.0633e-01, 3.9330e-01, 1.1121e+00, 5.2315e-01, 9.7753e-01,
         1.7648e-01, 1.1585e+00, 2.5359e-01, 1.0605e+00, 8.1897e-01, 4.4267e-01,
       

In [35]:
# 7. Get the sum of each row in z2
print(z2.sum(0))
# 8. Get the mean of each column in z2
print(z2.sum(1))

tensor([0.4301, 2.2343, 1.6697, 3.0166, 1.5686, 2.0009, 1.8310, 3.4345, 0.9624,
        1.8510, 2.9288, 3.0727, 3.5936, 2.7799, 2.1143, 2.3095, 2.9218, 4.6225,
        3.5774, 2.3221])
tensor([ 2.3914,  6.4013,  9.9046, 15.2250, 15.3193])


In [41]:
# 9. Reshape z to a 3D tensor (keep all the elements)
# Store reshaped tensor to z3
z3 = z.reshape(5,10,2)
# Print z3
print(z3)

tensor([[[0.0000e+00, 1.3805e-02],
         [2.7868e-02, 4.3810e-02],
         [6.0870e-02, 7.5849e-02],
         [3.5173e-02, 8.3995e-02],
         [1.2252e-01, 8.0283e-02],
         [1.8827e-01, 1.0047e-01],
         [9.7659e-04, 2.2346e-01],
         [1.7322e-01, 4.6248e-02],
         [2.7197e-01, 3.3043e-01],
         [2.6537e-01, 2.4681e-01]],

        [[1.3709e-01, 3.4649e-01],
         [7.1790e-02, 2.4125e-01],
         [2.2803e-01, 2.0790e-01],
         [4.9781e-01, 4.2878e-01],
         [1.6260e-01, 3.9493e-01],
         [1.0698e-01, 3.9700e-01],
         [6.1780e-01, 3.7665e-02],
         [3.5760e-01, 2.4723e-01],
         [1.6216e-01, 6.7896e-01],
         [6.4600e-01, 4.3326e-01]],

        [[3.3584e-02, 6.9944e-01],
         [6.0168e-01, 7.3181e-01],
         [7.3591e-01, 4.5424e-01],
         [7.1947e-01, 1.2861e-01],
         [3.9944e-01, 2.1196e-01],
         [3.0296e-01, 6.3400e-01],
         [7.2208e-01, 1.0558e+00],
         [6.7141e-01, 5.1035e-01],
         [1.5445